USE [master]
GO

/****** Object:  Database [PedroCovino]    Script Date: 02/02/2021 11:37:18 a. m. ******/
CREATE DATABASE [PedroCovino]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PedroCovino', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PedroCovino.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PedroCovino_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PedroCovino_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PedroCovino] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PedroCovino].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PedroCovino] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PedroCovino] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PedroCovino] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PedroCovino] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PedroCovino] SET ARITHABORT OFF 
GO

ALTER DATABASE [PedroCovino] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PedroCovino] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PedroCovino] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PedroCovino] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PedroCovino] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PedroCovino] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PedroCovino] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PedroCovino] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PedroCovino] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PedroCovino] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PedroCovino] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PedroCovino] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PedroCovino] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PedroCovino] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PedroCovino] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PedroCovino] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PedroCovino] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PedroCovino] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PedroCovino] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PedroCovino] SET  MULTI_USER 
GO

ALTER DATABASE [PedroCovino] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PedroCovino] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PedroCovino] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PedroCovino] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PedroCovino] SET  READ_WRITE 
GO


